DROP DATABASE IF EXISTS courses;
CREATE DATABASE courses;
use courses;
CREATE TABLE instructors (id INT AUTO_INCREMENT, name VARCHAR(20) UNIQUE NOT NULL, subject VARCHAR(20) NOT NULL, specialization VARCHAR(20) NOT NULL, experience_years INT, PRIMARY KEY (id));
CREATE TABLE course (id INT AUTO_INCREMENT, subject VARCHAR(20) NOT NULL, specialization VARCHAR(20), location_city VARCHAR(20), location_street VARCHAR(20), location_office INT, instructor_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (instructor_id) REFERENCES instructors (id));
CREATE TABLE students (id INT AUTO_INCREMENT, name VARCHAR(20) UNIQUE NOT NULL, phonenumber BIGINT, city VARCHAR(20), street VARCHAR(20), flat INT, PRIMARY KEY (id));
CREATE TABLE grades (id INT AUTO_INCREMENT, value INT, student_id INT, course_id INT, PRIMARY KEY (id), FOREIGN KEY (student_id)REFERENCES students(id),FOREIGN KEY (course_id)REFERENCES course(id));
CREATE TABLE reviews (id INT AUTO_INCREMENT, review VARCHAR(60), student_id INT, course_id INT, PRIMARY KEY (id), FOREIGN KEY (student_id)REFERENCES students(id),FOREIGN KEY (course_id)REFERENCES course(id));
CREATE TABLE students_courses (student_id INT, course_id INT, PRIMARY KEY (student_id,course_id), FOREIGN KEY (student_id)REFERENCES students(id), FOREIGN KEY (course_id)REFERENCES course(id));
CREATE TABLE roles (id INT AUTO_INCREMENT, name VARCHAR(20) UNIQUE NOT NULL, PRIMARY KEY (id));
CREATE TABLE users (id INT AUTO_INCREMENT, name VARCHAR(20) UNIQUE NOT NULL, password VARCHAR(50), role_id INT, PRIMARY KEY (id), FOREIGN KEY (role_id) REFERENCES roles(id));
INSERT INTO instructors (courses.instructors.name,courses.instructors.subject,courses.instructors.specialization,courses.instructors.experience_years) VALUES ('Jhon','Programming','java',13);
INSERT INTO instructors (courses.instructors.name,courses.instructors.subject,courses.instructors.specialization,courses.instructors.experience_years) VALUES ('Kyke','Programming','net',5);
INSERT INTO instructors (courses.instructors.name,courses.instructors.subject,courses.instructors.specialization,courses.instructors.experience_years) VALUES ('Kate','Language','english',3);
INSERT INTO instructors (courses.instructors.name,courses.instructors.subject,courses.instructors.specialization,courses.instructors.experience_years) VALUES ('Sam','Language','french',1);
INSERT INTO course (courses.course.subject,courses.course.specialization,courses.course.location_city,courses.course.location_street,courses.course.location_office,courses.course.instructor_id) VALUES ('Programming','java','London','Baker 22','44','1');
INSERT INTO course (courses.course.subject,courses.course.specialization,courses.course.location_city,courses.course.location_street,courses.course.location_office,courses.course.instructor_id) VALUES ('Programming','net','Minsk','Bryl 54','701','1');
INSERT INTO course (courses.course.subject,courses.course.specialization,courses.course.location_city,courses.course.location_street,courses.course.location_office,courses.course.instructor_id) VALUES ('Language','english','Minsk','Green 12','93','2');
INSERT INTO course (courses.course.subject,courses.course.specialization,courses.course.location_city,courses.course.location_street,courses.course.location_office,courses.course.instructor_id) VALUES ('Language','french','Minsk','Oktyabr 2','75','2');
